# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-17 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220516_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.SmallIntegerField(choices=[(1, '文件'), (2, '文件夹')], verbose_name='类型')),
                ('name', models.CharField(help_text='文件/文件夹名', max_length=32, verbose_name='名称')),
                ('key', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件存储在cos中的key')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='项目')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='web.File', verbose_name='父级目录')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='最近更新者')),
            ],
        ),
    ]
