# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-18 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20220518_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件路径'),
        ),
    ]
